services:
  app:
    image: analytic-api:v1
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8002:8002"
    volumes:
      - ./src:/code
    command: uvicorn main:app --host 0.0.0.0 --port 8002 --reload
    develop:
      watch:
        - action: rebuild
          path: dockerfile
        - action: rebuild
          path: reqirements.txt
        - action: rebuild
          path: docker-compose.yml
    networks:
      - analytic-api
    depends_on:
      db_service:
        condition: service_healthy
          
# postgresql+psycopg://root:2003@localhost:5432/analytic
  db_service:
    image: timescale/timescaledb:latest-pg17
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=2003
      - POSTGRES_DB=analytic
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d analytic"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    networks:
      - analytic-api

networks:
  analytic-api:
    driver: bridge
